"""
Track-03: a SAFE demo-level voice layer. No real telephony/TTS dependency --
`MockVoiceProvider` simulates a call attempt and always reports
`audio_available=False`. Mirrors llm/client.py's `LLMClient`/`MockLLMClient`
abstraction one layer up: `VoiceRecoveryProvider` is the interface,
`MockVoiceProvider` the only implementation this project ships (a real
telephony/TTS adapter is a documented future-work hook, not implemented
here -- see module docstring's "optional local TTS adapter" note in the
project's own brief).

The script itself is generated by llm/service.py::generate_voice_script
(Job 4, optional) and persisted as an ordinary LLMInvocation row
(task_name="voice_script_generation") -- this module ONLY represents the
call-ATTEMPT step that comes after the script exists; it has no table of
its own, one audit_log row (actor="voice") is enough to narrate it, same as
everywhere else in this codebase.
"""
from __future__ import annotations

import abc
from dataclasses import dataclass


@dataclass(frozen=True)
class VoiceCallResult:
    attempted: bool
    connected: bool
    audio_available: bool
    script_text: str
    provider_name: str
    error: str | None = None


class VoiceRecoveryProvider(abc.ABC):
    provider_name: str

    @abc.abstractmethod
    def place_call(self, script_text: str, customer_ref: str) -> VoiceCallResult:
        """Never raises -- any provider-level failure must be represented in
        the returned VoiceCallResult (attempted=True, connected=False,
        error=<reason>), the same fail-safe contract llm/client.py's
        LLMClient.complete() establishes one layer up."""


class MockVoiceProvider(VoiceRecoveryProvider):
    """Deterministic, offline -- makes NO real call, NO network request, NO
    TTS synthesis. `audio_available` is always False (brief: "The mock
    provider should simulate: generated script, audio_available=False")."""

    provider_name = "mock"

    def place_call(self, script_text: str, customer_ref: str) -> VoiceCallResult:
        return VoiceCallResult(
            attempted=True, connected=False, audio_available=False,
            script_text=script_text, provider_name=self.provider_name, error=None,
        )
