"""
Baselines -- for comparison against the AI-assisted policy in
evaluation/evaluate_policy.py. All three respect the same classification
gate as the main policy (retrying a hard-declined or already-cancelled
subscription doesn't make sense under any policy, naive or not) and the
same candidate-validity check. None of them tracks max-attempts or
duplicate-decision state -- those are specifically the AI-assisted policy's
guardrails (the brief's section 7 frames them under "Our Policy" / section
6), not properties of a simple comparison rule evaluated per-event.

IMPORTANT -- `rule_based_baseline` is BOTH an evaluation baseline AND the
LIVE operational fallback tier `policy/decision_engine.py` and
`policy/decision_engine_v4.py` call directly (`decide_engine` /
`decide_engine_v4`'s `fallback_type = rule_based_baseline(...)["selected_candidate_type"]`).
Every change below to `fixed_retry_baseline` / `rule_based_baseline` is
STRICTLY ADDITIVE to their returned dicts -- `selected_candidate_type` /
`selected_candidate_datetime` (the only two keys the operational policy
code ever reads) are computed EXACTLY as before, unchanged. New keys exist
purely for the evaluation baselines to read; the operational policy code
remains completely untouched.

BASELINE-FIDELITY FIX (see module-level additions below):
`fixed_retry_baseline` now exposes the FULL T+1/T+2/T+3 retry schedule the
original specification's "silent auto-retry once/day for 3 days, same
channel, then gives up" describes (previously only ever exposed a single
T+1 selection -- see FIXED_RETRY_SCHEDULE_CANDIDATE_TYPES below for exactly
how T+2 is represented given the existing candidate/counterfactual
framework has no native day-2 candidate type). `rule_based_baseline` now
also exposes `communication_actions` -- the specification's "one WhatsApp
nudge; one follow-up 3 days later" -- as a NEW, purely additive field; its
own retry-timing decision (payday_window / plus_1_day_morning / NO_ACTION)
is completely unchanged.
"""
from __future__ import annotations

from datetime import datetime, timedelta

from policy.guardrails import is_classification_allowed, validate_candidate
from policy.retry_candidates import Candidate, generate_candidates
from policy.scoring import score_candidate

NO_ACTION = "NO_ACTION"

PAYDAY_PROXIMITY_THRESHOLD_DAYS = 2  # baseline 3's "very close to payday" cutoff

# ---------------------------------------------------------------------------
# Fixed Retry's T+1/T+2/T+3 schedule.
#
# T+1 and T+3 reuse this project's EXISTING "plus_1_day_morning" /
# "plus_3_days" candidate identifiers and datetime formulas 1:1
# (policy/retry_candidates.py::generate_candidates) -- both already have
# real, independently-simulated outcome rows in
# data/raw/counterfactual_outcomes.csv (generated by
# data/generate_counterfactual_dataset.py, unmodified by this fix).
#
# T+2 has NO equivalent in that 5-candidate framework --
# policy/retry_candidates.py::CANDIDATE_TYPES was never extended with a 6th
# "day+2" type, and the counterfactual dataset was never generated with one
# either. Adding one now would mean regenerating the synthetic dataset with
# a NEW candidate/outcome definition -- exactly what this fix is instructed
# not to do ("do not invent a new outcome definition," "no dependency
# changes," "do not change the evaluation population"). T+2 is still
# SCHEDULED here (a real, distinct candidate_datetime -- "three retry
# opportunities exist" is genuinely true of this baseline's schedule, same
# time-of-day as T+1 per the specification's "silent auto-retry once/day"),
# but has no distinguishable simulated OUTCOME of its own; see
# evaluation/evaluate_decision_engine_v4.py::evaluate_events_v4 for exactly
# how the sequence is scored against the existing counterfactual machinery
# (T+2 contributes zero incremental recovery probability -- a deliberately
# conservative, non-invented choice, not an estimate).
# ---------------------------------------------------------------------------

FIXED_RETRY_SCHEDULE_CANDIDATE_TYPES = ["plus_1_day_morning", "plus_2_days_morning", "plus_3_days"]


def _fixed_retry_candidates(failure_timestamp: datetime) -> list[Candidate]:
    """The 3 scheduled Fixed Retry attempts, in order. Same channel/instrument
    as the original failed charge (this project has never modeled a
    different instrument for a retry -- there is nothing to change here),
    no customer communication (silent, per the specification), no learning,
    no personalization -- identical philosophy to every other candidate this
    baseline already used before this fix."""
    raw_times = {
        "plus_1_day_morning": (failure_timestamp + timedelta(days=1)).replace(hour=9, minute=0, second=0, microsecond=0),
        "plus_2_days_morning": (failure_timestamp + timedelta(days=2)).replace(hour=9, minute=0, second=0, microsecond=0),
        "plus_3_days": (failure_timestamp + timedelta(days=3)).replace(hour=12, minute=0, second=0, microsecond=0),
    }
    candidates = []
    for candidate_type in FIXED_RETRY_SCHEDULE_CANDIDATE_TYPES:
        dt = raw_times[candidate_type]
        candidates.append(
            Candidate(
                candidate_type=candidate_type,
                candidate_datetime=dt,
                hours_from_failure=round((dt - failure_timestamp).total_seconds() / 3600, 2),
                candidate_day_of_month=dt.day,
                candidate_day_of_week=dt.strftime("%A"),
                candidate_is_payday_aligned=False,  # Fixed Retry's cadence is calendar-day-offset only, never payday-aware -- that's Rule-Based's distinguishing behavior
                candidate_is_month_end_aligned=False,
                candidate_days_to_payday=-1,  # not meaningful for this baseline; never read by validate_candidate or by this baseline's own scoring below
            )
        )
    return candidates


# ---------------------------------------------------------------------------
# Rule-Based's communication dimension: one WhatsApp nudge (sent alongside
# the payday-timed retry), one follow-up 3 days later, then stop -- per the
# specification. Deterministic, fixed templates -- NEVER calls llm/service.py
# or any LLM (that would make this an LLM-driven baseline, which the
# specification's "hand-coded, no learning" baseline philosophy explicitly
# rules out; the live orchestrator's real LLM-generated outreach is a
# completely separate, unrelated code path -- recovery/orchestrator.py --
# untouched by this fix).
# ---------------------------------------------------------------------------

RULE_BASED_WHATSAPP_NUDGE_TEMPLATE = (
    "Your recent payment did not go through. We're retrying it automatically around your next payday -- "
    "please make sure funds are available."
)
RULE_BASED_WHATSAPP_FOLLOWUP_TEMPLATE = (
    "Reminder: your payment retry is still pending. Please check your payment method or ensure funds are available."
)
RULE_BASED_FOLLOWUP_OFFSET_DAYS = 3


def _no_action_result(event_id, subscription_id: str, reason: str) -> dict:
    return {
        "event_id": event_id,
        "subscription_id": subscription_id,
        "selected_candidate_type": NO_ACTION,
        "selected_candidate_datetime": None,
        "predicted_recovery_probability": None,
        "expected_recovery_value": None,
        "expected_incremental_value": None,
        "decision_reason": reason,
        "retry_schedule": [],  # additive -- see fixed_retry_baseline
        "communication_actions": [],  # additive -- see rule_based_baseline
    }


def no_recovery_baseline(event_id, subscription_id: str, **_ignored) -> dict:
    """BASELINE 1: never takes any action, regardless of context."""
    return _no_action_result(event_id, subscription_id, "baseline_no_recovery: no retry action is ever taken")


def fixed_retry_baseline(
    event_id,
    subscription_id: str,
    failure_timestamp: datetime,
    amount: float,
    classification_bucket: str,
    base_probability: float,
) -> dict:
    """BASELINE 2: the specification's "silent auto-retry once/day for 3
    days, same channel, then gives up" -- schedules THREE attempts
    (T+1/T+2/T+3, see `_fixed_retry_candidates`), validating each
    individually (subject to the shared classification/validity gates).

    `selected_candidate_type` / `selected_candidate_datetime` remain the
    FIRST valid attempt (T+1 in the normal case) -- UNCHANGED from this
    function's behavior before this fix, since those are the only two keys
    any existing caller (including the operational fallback tiers that
    import `rule_based_baseline`, not this function, but the same
    backward-compatibility guarantee applies) ever reads. `retry_schedule`
    is a NEW, additive field listing every VALID scheduled attempt in
    order -- consumed by evaluation/evaluate_decision_engine_v4.py to score
    the whole 3-day campaign against the existing counterfactual outcome
    rows for whichever of T+1/T+3 actually have one (see module docstring
    for why T+2 has none). `communication_actions` is always empty --
    Fixed Retry is SILENT, per the specification."""
    if not is_classification_allowed(classification_bucket):
        return _no_action_result(event_id, subscription_id, f"blocked_by_classification: bucket={classification_bucket!r}")

    schedule_candidates = _fixed_retry_candidates(failure_timestamp)
    valid_candidates = []
    invalid_reasons = []
    for candidate in schedule_candidates:
        valid, invalid_reason = validate_candidate(candidate, failure_timestamp)
        if valid:
            valid_candidates.append(candidate)
        else:
            invalid_reasons.append(f"{candidate.candidate_type}: {invalid_reason}")

    if not valid_candidates:
        return _no_action_result(
            event_id, subscription_id,
            f"blocked_invalid_candidate: all 3 scheduled attempts invalid ({'; '.join(invalid_reasons)})",
        )

    target = valid_candidates[0]
    scored = score_candidate(base_probability, target, amount)
    return {
        "event_id": event_id,
        "subscription_id": subscription_id,
        "selected_candidate_type": scored["candidate_type"],
        "selected_candidate_datetime": scored["candidate_datetime"],
        "predicted_recovery_probability": scored["predicted_recovery_probability"],
        "expected_recovery_value": scored["expected_recovery_value"],
        "expected_incremental_value": scored["expected_incremental_value"],
        "decision_reason": (
            "baseline_fixed_retry: silent auto-retry once/day for 3 days, same channel, then gives up "
            f"({len(valid_candidates)}/3 scheduled attempts valid: {[c.candidate_type for c in valid_candidates]})"
        ),
        "retry_schedule": [c.candidate_type for c in valid_candidates],
        "retry_schedule_datetimes": [c.candidate_datetime for c in valid_candidates],
        "communication_actions": [],
    }


def rule_based_baseline(
    event_id,
    subscription_id: str,
    failure_timestamp: datetime,
    amount: float,
    classification_bucket: str,
    base_probability: float,
) -> dict:
    """
    BASELINE 3: very close to payday -> payday_window, otherwise ->
    plus_1_day_morning. Never selects immediate / plus_3_days /
    month_end_window -- deliberately simple and explainable.
    """
    if not is_classification_allowed(classification_bucket):
        return _no_action_result(event_id, subscription_id, f"blocked_by_classification: bucket={classification_bucket!r}")

    candidates = {c.candidate_type: c for c in generate_candidates(failure_timestamp)}
    payday = candidates["payday_window"]
    morning = candidates["plus_1_day_morning"]

    if payday.candidate_days_to_payday <= PAYDAY_PROXIMITY_THRESHOLD_DAYS:
        preferred, rule = payday, f"very close to payday (<= {PAYDAY_PROXIMITY_THRESHOLD_DAYS}d) -> payday_window"
    else:
        preferred, rule = morning, "not close to payday -> plus_1_day_morning"

    valid, invalid_reason = validate_candidate(preferred, failure_timestamp)
    if not valid:
        # Simple, explainable fallback -- try the other of the two rule candidates before giving up.
        fallback = morning if preferred is payday else payday
        fallback_valid, fallback_invalid_reason = validate_candidate(fallback, failure_timestamp)
        if not fallback_valid:
            return _no_action_result(
                event_id, subscription_id, f"blocked_invalid_candidate: {invalid_reason}; fallback also invalid: {fallback_invalid_reason}"
            )
        preferred, rule = fallback, f"{rule} was invalid ({invalid_reason}); fell back to the other candidate"

    scored = score_candidate(base_probability, preferred, amount)

    # BASELINE-FIDELITY FIX: the specification's communication dimension --
    # "one WhatsApp nudge; one follow-up 3 days later; then stop" -- attached
    # to the SAME retry decision computed above, never changing it. Fixed,
    # deterministic templates -- no LLM call (see module docstring).
    retry_dt = scored["candidate_datetime"]
    communication_actions = [
        {"channel": "whatsapp", "type": "nudge", "scheduled_datetime": retry_dt, "message_text": RULE_BASED_WHATSAPP_NUDGE_TEMPLATE},
        {
            "channel": "whatsapp", "type": "follow_up", "scheduled_datetime": retry_dt + timedelta(days=RULE_BASED_FOLLOWUP_OFFSET_DAYS),
            "message_text": RULE_BASED_WHATSAPP_FOLLOWUP_TEMPLATE,
        },
    ]

    return {
        "event_id": event_id,
        "subscription_id": subscription_id,
        "selected_candidate_type": scored["candidate_type"],
        "selected_candidate_datetime": scored["candidate_datetime"],
        "predicted_recovery_probability": scored["predicted_recovery_probability"],
        "expected_recovery_value": scored["expected_recovery_value"],
        "expected_incremental_value": scored["expected_incremental_value"],
        "decision_reason": f"baseline_rule_based: {rule}",
        "retry_schedule": [scored["candidate_type"]],
        "communication_actions": communication_actions,
    }
